name: Build and deploy ASP.Net Core app to Azure Web App - appservice-helloworld-uksouth-002

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # or whatever version you're using

      - name: Build project
        run: dotnet build HelloWorld/HelloWorld.csproj --configuration Release

      - name: Publish project
        run: dotnet publish HelloWorld/HelloWorld.csproj -c Release -o '${{env.DOTNET_ROOT}}/myapp'

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./published

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2079A00C05A342DE9016BBD7EA493DD2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C7E09E7A3CF4CC083399D1EB4459DA3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONI_
