name: Build and Deploy .NET App to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: appservice-helloworld-uksouth-001
  AZURE_WEBAPP_PACKAGE_PATH: '.' # This will be overridden if necessary
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore 1HelloWorld.sln

      - name: Build
        run: dotnet build 1HelloWorld.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test 1HelloWorld.sln --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish 1HelloWorld.sln --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./publish
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
